using GameNetcodeStuff;

namespace LethalAchievements.Config;

/// <summary>
///     The context in which an achievement is being checked.
///     This is used by <see cref="ICondition"/> and generated by <see cref="ITrigger"/>s.
/// </summary>
public struct Context
{
    /// <summary>
    ///    The achievement being checked.
    /// </summary>
    public ConfigAchievement Achievement;
    
    /// <summary>
    ///     The player being checked.
    /// </summary>
    public PlayerControllerB? Player;
    
    /// <summary>
    ///     The enemy being checked.
    /// </summary>
    public EnemyAI? Enemy;
 
    /// <summary>
    ///     Creates a context with default values.
    ///     <list type="bullet">
    ///         <item>
    ///             <description><see cref="Achievement"/> is set to null.</description>
    ///         </item>
    ///         <item>
    ///             <description><see cref="Player"/> is set to the local player.</description>
    ///         </item>
    ///          <item>
    ///             <description><see cref="Enemy"/> is set to null.</description>
    ///         </item>
    ///     </list>
    /// </summary>
    /// <returns></returns>
    public static Context Default()
    {
        return new Context {
            Player = StartOfRound.Instance.localPlayerController
        };
    }
}